### ISSUE TITLE
Solution in vanilla js

### ISSUE THREAD

**Issue by shubhamdhillon** [Crunchwrap78/clicks-subset#1]
Sir can you please explain the calculateIfHourBetweenClick method   and 
CheckIfOverHourPeriod   method . Apparently the result seems to be coming out wrong with this .

**Comment by Crunchwrap78** [comment]
Ah there's a lot of context to this not included. Sorry for the late reply 

1.For each IP within each one hour period, only the most expensive click is placed into the
result set.
2. If more than one click from the same IP ties for the most expensive click in a one hour
period, only place the earliest click into the result set.
3. If there are more than 10 clicks for an IP in the overall array of clicks, do not include any
of those clicks in the result set. 

The results come out correctly, but there are unique edge cases in the set
